# Site settings
title: STILT Model
email:
description: Stochastic Time-Inverted Lagrangian Transport Model

baseurl: "/stilt/" # the subpath of your site, e.g. /blog/
url: "https://uataq.github.io" # the base hostname & protocol for your site

social:
  - title: github
    url: http://github.com/uataq/stilt/

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
